### ISSUE TITLE
[podman] update in 1.11.0-14

### ISSUE THREAD

**Issue by gtrabanco** [boostchicken/udm-utilities#233]
**Describe the bug**
I could not get into `unifi-os shell`. So, as you can see in **Workaround** part I had to disable the startup update script for `podman`, `runc` & `conmon` because it fails when updating is done.

I had the issue described in [official forum](https://community.ui.com/releases/UniFi-OS-Dream-Machines-1-11-0-14/71916646-d8f6-41c0-b145-2fbe2db7c278#comment/eb477247-f30a-4ed7-b499-c0b7298afd3a) (log is also in the bottom of this issue) by error thinking was an update problem to beta 1.11.0.14.

The problems are:
* Can not get into `unifi-os` container.
* The startup of other containers different than `unifi-os` is not done.

**To Reproduce**
1. open udm shell
2. `unifi-os`
Only when you have script [01-podman-update.sh](https://github.com/boostchicken/udm-utilities/blob/master/podman-update/01-podman-update.sh).

**Expected behavior**
Update podman, runc & conmon and start all containers without problems.

**Screenshots**

**UDM Information**
```
# ubnt-device-info summary
Device information summary:
        Subsystem ID: ea15
              Family: UniFi Dream Machine (UDM)
               Model: UniFi Dream Machine Pro (UDM-Pro)
 Default MAC address: e0:63:da:5a:cc:41
Default IPv4 address: 127.0.0.1
            Firmware: 1.11.0-14 (1.11.0-14)
```

**Log report**
```bash
Welcome to UbiOS


By logging in, accessing, or using the Ubiquiti product, you
acknowledge that you have read and understood the Ubiquiti
License Agreement and agree to be bound by its terms.


  ___ ___      .__________.__
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2021
 |   |  |   |  \  ||  \   |  |   Ubiquiti Inc.
 |______|___|  /__||__/   |__|
            |_/                  http://www.ui.com


      Welcome to UniFi Dream Machine!
# unifi-os shell
WARN[0000] Failed to add conmon to cgroupfs sandbox cgroup: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus.effective: no such file or directory
Error: OCI runtime error: panic: expected "name=systemd" path to be unified path "/sys/fs/cgroup/devices/libpod_parent/libpod-3b8e789d9346cb38ed1b8ddf2c003c4f9eda19524acc8896093eec4561ed4359", got "/sys/fs/cgroup/systemd/libpod_parent/libpod-3b8e789d9346cb38ed1b8ddf2c003c4f9eda19524acc8896093eec4561ed4359"


goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer.getUnifiedPath(0x4000246c30, 0x555b697900, 0x0)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:59 +0x2cc
github.com/opencontainers/runc/libcontainer.cgroupfs2.func1(0x40001d5730, 0x4000246c30, 0x4a, 0x7ffefeaedf)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:111 +0x30
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).Load(0x4000200000, 0x7ffefeaedf, 0x40, 0x0, 0x0, 0x1, 0x8)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:321 +0x14c
main.getContainer(0x40001fe160, 0x555b6afb14, 0x8, 0x1, 0x40001c53bc)
	github.com/opencontainers/runc/utils_linux.go:89 +0x9c
main.execProcess(0x40001fe160, 0x0, 0x0, 0x0)
	github.com/opencontainers/runc/exec.go:114 +0x30
main.glob..func5(0x40001fe160, 0x555babbd80, 0x40001c5518)
	github.com/opencontainers/runc/exec.go:104 +0x6c
github.com/urfave/cli.HandleAction(0x555b7ae560, 0x555b851070, 0x40001fe160, 0x40001fe160, 0x0)
	github.com/urfave/cli@v1.22.1/app.go:523 +0x124
github.com/urfave/cli.Command.Run(0x555b6abc4c, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x555b6c2b5b, 0x28, 0x0, ...)
	github.com/urfave/cli@v1.22.1/command.go:174 +0x408
github.com/urfave/cli.(*App).Run(0x40001f8000, 0x40000c8000, 0xe, 0xe, 0x0, 0x0)
	github.com/urfave/cli@v1.22.1/app.go:276 +0x588
main.main()
	github.com/opencontainers/runc/main.go:165 +0xa3c
```

I tried to execute the script manually to see if there is any error in the process but no error was given.

**Workaround**

To solve the issue I had to disable `01-podman-update.sh` on startup and reboot.

**NOTE**: Rename of `/usr/bin/podman.old`, `/usr/bin/runc.old` and `/usr/libexec/podman/conmon.old` to its normal values did not resolve the issue.

**Comment by MizterB** [comment]
I just installed the latest podman script, and 3.3.0 seems to be working fine on the latest UDMP software.

However, every time I run the `podman` command, I get the following warning:
`WARN[0000] Failed to decode the keys ["storage.options.ostree_repo"] from "/etc/containers/storage.conf".`

Is anyone else seeing this behavior?

**Comment by leeaash** [comment]
> I just installed the latest podman script, and 3.3.0 seems to be working fine on the latest UDMP software.
> 
> However, every time I run the `podman` command, I get the following warning:
> `WARN[0000] Failed to decode the keys ["storage.options.ostree_repo"] from "/etc/containers/storage.conf".`
> 
> Is anyone else seeing this behavior?

I did. I comment `ostree_repo =  “”` in /etc/containers/storage.conf, then the warning gone. But I don’t know the comment if have any other impact.

**Comment by MizterB** [comment]
Got it.  Does that file persist across reboots & upgrades?  Or do I need to comment out via a on_boot.d script?

**Comment by leeaash** [comment]
> Got it. Does that file persist across reboots & upgrades? Or do I need to comment out via a on_boot.d script?

You can add a line `sed -i 's/ostree_repo = ""/#ostree_repo = ""/' /etc/containers/storage.conf ` in 01-podman-update.sh

**Comment by gtrabanco** [comment]
@boostchicken not sure if you have updated the script pretending that this is solved but this is not. I am receiving the same issue and adding another one:

```bash
# unifi-os shell
WARN[0000] Failed to decode the keys ["storage.options.ostree_repo"] from "/etc/containers/storage.conf".
```

After executing this script: https://github.com/boostchicken/udm-utilities/blob/3dc5774c00aeac234bf50a62a0dd350e3bafac91/podman-update/01-podman-update.sh

**Comment by boostchicken** [comment]
I added that line to the script.  Is everyone comfortable wit hthe podman upgrade working now? If so I will close the issue

**Comment by gtrabanco** [comment]
Sorry but same issue when executing `unifi-os shell`

**All the steps and output:**

```bash
# cd /mnt/data/
# curl -O https://raw.githubusercontent.com/boostchicken/udm-utilities/master/podman-update/01-podman-update.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1701  100  1701    0     0   6300      0 --:--:-- --:--:-- --:--:--  6300
# ls
01-podman-update.sh  crash-data           lost+found           ssh                  udapi-config         ulcmd
adguard              dpi-tracer           on_boot.d            system               udm-le               unifi-os
backupftp            log                  podman               traces               ui-db                wireguard
# chmod u+x 01-podman-update.sh
# ./01-podman-update.sh
# unifi-os shell
WARN[0000] Failed to add conmon to cgroupfs sandbox cgroup: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus.effective: no such file or directory
Error: OCI runtime error: panic: expected "name=systemd" path to be unified path "/sys/fs/cgroup/devices/libpod_parent/libpod-3b8e789d9346cb38ed1b8ddf2c003c4f9eda19524acc8896093eec4561ed4359", got "/sys/fs/cgroup/systemd/libpod_parent/libpod-3b8e789d9346cb38ed1b8ddf2c003c4f9eda19524acc8896093eec4561ed4359"

goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer.getUnifiedPath(0x400029ae10, 0x55869b5400, 0x0)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:59 +0x2cc
github.com/opencontainers/runc/libcontainer.cgroupfs2.func1(0x4000231730, 0x400029ae10, 0x4a, 0x7ffe24eedf)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:111 +0x30
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).Load(0x400023a090, 0x7ffe24eedf, 0x40, 0x0, 0x0, 0x1, 0x8)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:321 +0x14c
main.getContainer(0x400025a160, 0x55869c5e78, 0x8, 0x1, 0x40002233b8)
	github.com/opencontainers/runc/utils_linux.go:89 +0x9c
main.execProcess(0x400025a160, 0x0, 0x0, 0x0)
	github.com/opencontainers/runc/exec.go:114 +0x30
main.glob..func5(0x400025a160, 0x5586de93c0, 0x40002234f8)
	github.com/opencontainers/runc/exec.go:104 +0x6c
github.com/urfave/cli.HandleAction(0x5586ab6d60, 0x5586b63bc8, 0x400025a160, 0x400025a160, 0x0)
	github.com/urfave/cli@v1.22.1/app.go:523 +0x124
github.com/urfave/cli.Command.Run(0x55869c1f3e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55869d9b5a, 0x28, 0x0, ...)
	github.com/urfave/cli@v1.22.1/command.go:174 +0x408
github.com/urfave/cli.(*App).Run(0x4000252000, 0x400013c000, 0xe, 0xe, 0x0, 0x0)
	github.com/urfave/cli@v1.22.1/app.go:276 +0x588
main.main()
	github.com/opencontainers/runc/main.go:163 +0xa7
```

**Comment by MizterB** [comment]
The latest version has resolved the `ostree_repo` message for me.  No issues.

**Comment by justfly1111** [comment]
im having this issue where is the fix?

**Comment by renedis** [comment]
Have the same issue on 1.11.0-16
Running on the old 1.61 podman works fine but is not really wanted. Updating to new 3.3.0 podman causes a lot of issues.

**Comment by leeaash** [comment]
Is it safe to upgrade to 1.10.4 which was released couple days ago?

**Comment by dvcrn** [comment]
Network controller issue was related to system running out of space and had nothing to do with podman 3.3.0 upgrade so scrap that

**Comment by renedis** [comment]
Hi @boostchicken, version 3.40 is also not uploaded to "https://github.com/boostchicken/udm-utilities/tree/master/podman-update/bin". 3.3.0 is the latest download available. Also the shell script is pointing to 3.3.0. Does version 3.4.0 have changes regarding to systemd?

**Comment by boostchicken** [comment]
This is now fixed

**Comment by fonix232** [comment]
@boostchicken I'm sorry to report that it isn't, in fact, fixed. I just did a clean install on 1.11.0-21, and I'm still getting the exact same crash, and no access to `unifi-os shell`.

Did you mean to push changes to the repo? It was last updated 4 days ago.

**Comment by frznfngrs** [comment]
issue still present on 1.11.0-21 & 1.11.0-19

**Comment by dvcrn** [comment]
I'd recommend leaving Podman on the old version for the time being unless you really need one of the newer versions features

**Comment by frznfngrs** [comment]
Do you know how to safely roll back podman?   Attempting to use podman.old results in a very similar error message.

**Comment by gtrabanco** [comment]
> 

In the first message there is a workaround to use old podman. Basically avoid the update by disabling the update script and reboot.

**Comment by dvcrn** [comment]
> Do you know how to safely roll back podman? Attempting to use podman.old results in a very similar error message.

Yes, like gtrabanco said, just don't execute the podman update script and reboot. The UDM always goes back to it's initial state, then executes your boot scripts one by one
